Fixed UIScrollView (IDL_ViewGroup) onLayoutWithFrame to account for m…
J-Rojas/iDroidLayout pull request #3
Opened 2016-09-22 22:41 UTC by adhar

…ultiple subviews when computing content size/width

2016-10-03 23:35 UTC, J-Rojas commented on iDroidLayout/Widgets/Categories/UIScrollView+IDL_ViewGroup.m
> +    self.contentSize = CGSizeMake([self.subviews count] * (maxX + padding.right), maxY + padding.bottom);
This does not appear to be correct. The algorithm above uses maxX to track the width of the entire content area by adding up the child's x position plus the width. If the children are laid out horizontally, this should produce a content size based on the position of the right most child + it's width + the padding on the right side.

Your change here multiplies the sum of maxX + padding.right by the number of subviews. Assuming that maxX is somehow calculated incorrectly, this still does not at all seem correct as you would be adding the right padding several times.

2016-10-13 06:21 UTC, adhar commented on iDroidLayout/Widgets/Categories/UIScrollView+IDL_ViewGroup.m
> +    self.contentSize = CGSizeMake([self.subviews count] * (maxX + padding.right), maxY + padding.bottom);
That does seem to be the intent of the onLayoutFrame method but note that the line "NSInteger count = MIN(1, [self.subviews count]);" ensures that only the first scroll view child is ever visited. Similarly in onMeasureWithWidthMeasureSpec, only the first child is properly measured based on the layout params. I'm not sure why this constraint is in place but I've removed this for now.

In order for maxX to be correctly computed above, the left margin for each child must also be set so I've made that change in OnboardingScrollableSeriesController as well (see feature/onboarding-fixes).

This set of fixes is working well for me on my iPhone 6 device running iOS 10 but not on my iPhone 6 simulator with Xcode 8. For some reason, the scroll view is only reporting a single subview when using the simulator via Xcode 8; with AppCode-EAP (or previously Xcode 7), however, these fixes work on the same simulator. Rather bizarre but just an FYI.

2016-10-13 16:54 UTC, J-Rojas requested changes

2016-10-13 16:54 UTC, J-Rojas commented on iDroidLayout/Widgets/Categories/UIScrollView+IDL_ViewGroup.m
> +    self.contentSize = CGSizeMake([self.subviews count] * (maxX + padding.right), maxY + padding.bottom);
Okay, I would suggest making the change specifically to NSInteger count = self.subviews.count instead and eliminating the change you made. 

Your change assumes the width is the same for every child and it incorrectly multiplies the parent's right padding for every child.

2016-10-14 04:19 UTC, merged